title: "Yerevan Garage Sale"
description: "Доска частных объявлений в городе Ереван. Здесь Вы можете купить бывшие в употреблении или новые вещи у тех, кому они больше не нужны."
author: demansh
logo: "/assets/img/favicon/android-chrome-512x512.png"
remote_theme: jekyll/minima
markdown: kramdown
exclude: [fetch_data.py, requirements.txt, .github, docs.md]
url: "https://demansh.github.io"
baseurl: "/sell"
permalink: /posts/:title
telegram_channel_name: baraxolka_in_armenia
future: true
plugins:
  - jekyll-seo-tag