title: "Барахолка в Ереване"
description: "Доска частных объявлений в городе Ереван. Здесь Вы можете купить б/у или новые вещи у тех, кому они больше не нужны."
author: Garage Sale Yerevan
logo: "/assets/img/favicon/android-chrome-512x512.png"
remote_theme: jekyll/minima
markdown: kramdown
exclude:
  - fetch_data.py
  - requirements.txt
  - .github
  - docs.md
  - fetch_tg.py
  - llm_utils.py
  - config.py
  - image_optimizer.py
  - setup.sh
  - last_id.txt
  - my_session.session
  - gen_session.py
  - venv/
  - Gemfile
  - Gemfile.lock
  - README.md
url: "https://yerevansale.top"
baseurl: ""
permalink: /posts/:title
telegram_channel_name: baraxolka_in_armenia
future: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
